### ISSUE TITLE
Error in lm_resid_llt(X, Y) : could not find function "lm_resid_llt"

### ISSUE THREAD

**Issue by plycs1994** [jianan/qtlpvl#10]
Hello

Using R version 4.0.0 and has been tried on multiple computers.
I am following the "Introduction to qtlpvl" guide - the following code runs fine:
```
library(qtlpvl)
data(fake.phenos)
data(listeria)
listeria <- calc.genoprob(listeria, step=1)
chr <- 1
plotLOD(Y=fake.phenos, cross=listeria, chr=chr)
```
However when performing the multi-trait mapping I get the following error:
```
out <- scanone.mvn(cross=listeria, Y=fake.phenos, chr=chr)

Error in lm_resid_llt(X, Y) : could not find function "lm_resid_llt"
```
I get the same error if using my own data too. It appears to come from calling the lm.resid() function within scanone.mvn and I am ignorant of how to fix this. I hope this can be resolved - thank you!!

**Comment by jianan** [comment]
It seems `devtools` install the package from `HEAD` by default now, while this package should be installed from `master` branch.

Please try reinstall the package with the following command:
```
devtools::install_github('jianan/qtlpvl', ref="master")
```

**Comment by plycs1994** [comment]
Thank you - this has fixed this error
