### ISSUE TITLE
no visible biding for global variable

### ISSUE THREAD

**Issue by kbroman** [jianan/qtlpvl#6]
`R CMD check` gives the following `NOTE`:

```
* checking R code for possible problems ... NOTE
count.trans: no visible binding for global variable ‘is.trans’
find.trans: no visible binding for global variable ‘is.trans’
get.chr.info: no visible binding for global variable ‘pos’
scantwo.mvn: no visible global function definition for ‘pillai’
```

I don't quite understand the use of `is.trans` and `pos`, and I can't find a function definition for `pillai`.

**Comment by jianan** [comment]
`is.trans` and `pos` are variables in data.frame, I change the code to not using `subset` or `plyr::ddply` so R check don't complain anymore. 
`pillai` is an old function that no longer exists, I updated `scantwo.mvn` to use the new function as same as in `scanone.mvn` to calculate LOD score.
